/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmTextConverter.java
 *
 * Created on Feb 21, 2011, 9:51:45 PM
 */

package com.cis238.demos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ARMSTROD
 */
public class frmTextConverter extends javax.swing.JFrame {

    // global variables
    File myFile;

    /** Creates new form frmTextConverter */
    public frmTextConverter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtaOriginal = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConverted = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileOpen = new javax.swing.JMenuItem();
        mnuFileConvert = new javax.swing.JMenuItem();
        mnuFileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaOriginal.setColumns(20);
        jtaOriginal.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jtaOriginal.setRows(5);
        jScrollPane2.setViewportView(jtaOriginal);

        jtaConverted.setColumns(20);
        jtaConverted.setRows(5);
        jScrollPane1.setViewportView(jtaConverted);

        mnuFile.setText("File");

        mnuFileOpen.setMnemonic('O');
        mnuFileOpen.setText("Open");
        mnuFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileOpen);

        mnuFileConvert.setMnemonic('C');
        mnuFileConvert.setText("Convert");
        mnuFileConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileConvertActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileConvert);

        mnuFileExit.setMnemonic('x');
        mnuFileExit.setText("Exit");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileExit);

        jMenuBar1.add(mnuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileOpenActionPerformed
        // clear the text area
        this.jtaOriginal.setText(null);
        this.jtaConverted.setText(null);

        //get file to open from the user
        JFileChooser myChooser = new JFileChooser();
        myChooser.showOpenDialog(jtaOriginal);

        // get file object
        myFile = new File(myChooser.getSelectedFile().getPath());

        try
        {
            // create file reader
            FileReader myReader = new FileReader(myFile);

           //create buffered reader
           BufferedReader myBuffer = new BufferedReader(myReader);

           // read a line from the text file
           String strLine = myBuffer.readLine();

           // loop to get the rest of the lines
           while(strLine != null)
           {
               this.jtaOriginal.append(strLine);
               this.jtaOriginal.append("\n");
               strLine = myBuffer.readLine();
           }

           // close stuff
           myBuffer.close();
           myReader.close();

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_mnuFileOpenActionPerformed

    private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileExitActionPerformed
        // exit app
        System.exit(0);

    }//GEN-LAST:event_mnuFileExitActionPerformed

    private void mnuFileConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileConvertActionPerformed
        //get lines from text area into an array
        String strLines[] = jtaOriginal.getText().split("\\n");
        
        //loop through all elements in the array
        for(String s: strLines)
        {
            //pick out first and last names
            this.jtaConverted.append(s.substring(33, 49).trim()+ " ");
            this.jtaConverted.append(s.substring(8, 33).trim());
            this.jtaConverted.append("\n");
            
            //address line
            this.jtaConverted.append(s.substring(50, 90).trim());
            this.jtaConverted.append("\n");
            
            //city st zip
            this.jtaConverted.append(s.substring(90, 115).trim() + ", ");
            this.jtaConverted.append(s.substring(115, 117) + " ");
            this.jtaConverted.append(s.substring(117, 122));
            this.jtaConverted.append("\n");
            
            //blank line between addresses
            this.jtaConverted.append("\n");
        }
    }//GEN-LAST:event_mnuFileConvertActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTextConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtaConverted;
    private javax.swing.JTextArea jtaOriginal;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFileConvert;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenuItem mnuFileOpen;
    // End of variables declaration//GEN-END:variables

}
